version : '3'
services:
    app:
        container_name: node-challenge
        restart: always
        build: .
        ports: 
            - '3000:3000'
        volumes: 
            - ./usr:/src/app
